// services/v4/VeoFailureKnowledge.mjs
//
// AUTO-GENERATED by VeoFailureKnowledgeBuilder. DO NOT EDIT BY HAND.
//
// This file is the runtime artifact of the Veo Failure-Learning Agent. It is
// rewritten in place by services/v4/VeoFailureKnowledgeBuilder.js on a nightly
// cron (02:00 UTC) and on threshold-triggered incremental updates. The source
// of truth is the Supabase veo_failure_signatures table; this file is the
// projection of that table that VeoService and the screenplay-prompt builder
// import at runtime.
//
// Initial seed (2026-05-06): hand-authored from:
//   - VeoPromptSanitizer.js content-filter signatures
//   - Real production failures observed in logs.txt
//     ("This prompt contains words that violate Vertex AI's usage guidelines"
//      → forced Kling fallback on action beat s1b2)
//
// Consumers:
//   - services/VeoService.js              → applyPreflightRules() before tier 0 submission
//   - services/v4/VeoFailureGuidance.js   → cached facade; invalidates on rewrite
//   - public/components/brandStoryPromptsV4.mjs → optional system-prompt block
//   - services/BrandStoryService.js       → loads once per episode, passes to prompts
//
// Why a checked-in artifact (instead of a runtime DB read):
//   - read-path latency: zero DB round-trips per Veo call
//   - reviewability: every regen is a diff in source control on next deploy
//   - cache-friendly: dynamic import() hits Node's module cache after first load
//   - matches the assets/luts/library.json pattern (commit 2c571e2)

export const VEO_FAILURE_KNOWLEDGE_VERSION = '2026.05.06.0000-seed';
export const VEO_FAILURE_LAST_UPDATED = '2026-05-06T00:00:00.000Z';
export const VEO_FAILURE_SOURCE = 'seed'; // 'seed' on initial commit, 'agent' on every regen

// ─────────────────────────────────────────────────────────────────────
// Signature catalogue — one entry per active veo_failure_signatures row
// ─────────────────────────────────────────────────────────────────────

export const VEO_FAILURE_SIGNATURES = [
  {
    key: 'persona_possessive_bodypart',
    failure_mode: 'content_filter_prompt',
    pattern_description:
      'Possessive persona-name + body-part phrasing trips Vertex\'s person-identity filter. ' +
      'Production example: "A luxury silver wristwatch on Leo\'s wrist." ' +
      'Support code 29310472: "The prompt could not be submitted. This prompt contains words that violate Vertex AI\'s usage guidelines."',
    occurrence_count: 0, // accumulated by the agent over time
    severity: 'high',
    status: 'active',
    avoid_phrases: [
      "<persona>'s wrist",
      "<persona>'s hand",
      "<persona>'s hands",
      "<persona>'s arm",
      "<persona>'s face",
      "<persona>'s lips",
      "<persona>'s neck",
      "<persona>'s chest"
    ],
    safe_alternatives: [
      'in frame',
      'held in close detail',
      'cradled by gloved hands',
      'resting on a marble surface',
      'at the centre of the composition'
    ],
    gemini_directive:
      'Do not write "<persona-name>\'s <body-part>" — Vertex content filter rejects this. ' +
      'For INSERT_SHOT subject_focus, REACTION descriptions, and B_ROLL specs, use neutral product-hero framings ' +
      '("in frame", "held in close detail") instead of possessive-name + body-part constructions.',
    preflight_rule: {
      regex: "\\b([A-Z][a-zA-Z]+)'s\\s+(wrist|hand|hands|arm|arms|fingers|finger|palm|neck|chest|face|lips|eyes|hair|shoulder|shoulders|leg|legs|feet|foot|body|back|hip|hips|waist)\\b",
      flags: 'g',
      rewrite: 'in frame'
    },
    model_scope: ['veo-3.1-vertex', 'veo-3.1-fast', 'veo-3.1-standard']
  },
  {
    key: 'pronoun_bodypart',
    failure_mode: 'content_filter_prompt',
    pattern_description:
      'Pronoun + body-part ("her wrist", "his hand", "their fingers"). Triggers the same person-identity ' +
      'filter as possessive-name + body-part when combined with reference images via first_frame.',
    occurrence_count: 0,
    severity: 'medium',
    status: 'active',
    avoid_phrases: [
      'her wrist', 'her hand', 'her hands', 'her face',
      'his wrist', 'his hand', 'his hands', 'his face',
      'their wrist', 'their hand', 'their hands', 'their face'
    ],
    safe_alternatives: [
      'in frame', 'held in close detail', 'cradled in frame'
    ],
    gemini_directive:
      'Avoid pronoun + body-part constructions ("her wrist", "his hand") in beats where personas are anchored ' +
      'via first-frame imagery. Use neutral framings instead.',
    preflight_rule: {
      regex: "\\b(his|her|their)\\s+(wrist|hand|hands|arm|arms|fingers|finger|palm|neck|chest|face|lips|eyes|hair|shoulder|shoulders|leg|legs|feet|foot|body|back|hip|hips|waist)\\b",
      flags: 'gi',
      rewrite: 'in frame'
    },
    model_scope: ['veo-3.1-vertex', 'veo-3.1-fast', 'veo-3.1-standard']
  },
  {
    key: 'image_violates_guidelines',
    failure_mode: 'content_filter_image',
    pattern_description:
      'Vertex image-safety filter rejected the first_frame anchor image (not the prompt text). ' +
      'No amount of prompt-text rewriting fixes this — only regenerating the first frame ' +
      '(tier2.5-regen-frame callback) or dropping the anchor (tier3-no-image text-only) recovers.',
    occurrence_count: 0,
    severity: 'high',
    status: 'active',
    avoid_phrases: [],
    safe_alternatives: [],
    gemini_directive:
      'When authoring beats with persona anchoring, prefer compositions that emphasise wardrobe, environment, ' +
      'and product over close-up persona physicality. Reduces image-safety rejection rate on the persona-lock first frame.',
    preflight_rule: null, // image rejections are handled at the IMAGE layer, not the prompt layer
    model_scope: ['veo-3.1-vertex', 'veo-3.1-fast', 'veo-3.1-standard']
  },
  {
    key: 'high_load_transient',
    failure_mode: 'high_load',
    pattern_description:
      'Vertex AI Veo returned "The service is currently experiencing high load". Transient infra issue. ' +
      'Not prompt-related — backoff or fallback to Kling is the only mitigation.',
    occurrence_count: 0,
    severity: 'low',
    status: 'active',
    avoid_phrases: [],
    safe_alternatives: [],
    gemini_directive: '', // transient infra — no prompt-level guidance helps
    preflight_rule: null,
    model_scope: ['veo-3.1-vertex', 'veo-3.1-fast', 'veo-3.1-standard']
  }
];

// ─────────────────────────────────────────────────────────────────────
// Public API consumed by VeoService + screenplay prompt builder
// ─────────────────────────────────────────────────────────────────────

/**
 * Build a system-prompt block that Gemini uses while generating screenplays
 * (or per-beat Veo prompts). Returns an empty string when there are no
 * active gemini_directive entries — keeping the prompt clean during the
 * cold-start window before any signatures have been learned.
 *
 * @param {Object} [opts]
 * @param {string} [opts.modelId='veo-3.1-vertex'] - filter signatures by model_scope
 * @param {string[]} [opts.minSeverity=['low','medium','high','critical']] - severity allowlist
 * @returns {string}
 */
export function getGeminiSystemPromptBlock(opts = {}) {
  const {
    modelId = 'veo-3.1-vertex',
    minSeverity = ['low', 'medium', 'high', 'critical']
  } = opts;

  const directives = VEO_FAILURE_SIGNATURES
    .filter(s => s.status === 'active')
    .filter(s => !modelId || (s.model_scope || []).includes(modelId))
    .filter(s => minSeverity.includes(s.severity))
    .map(s => s.gemini_directive)
    .filter(d => typeof d === 'string' && d.trim().length > 0);

  if (directives.length === 0) return '';

  const header =
    '═══════════════════════════════════════════════════════════════\n' +
    'KNOWN VEO FAILURE PATTERNS — avoid these at authorship time\n' +
    '═══════════════════════════════════════════════════════════════\n' +
    `(Auto-learned from production failures. Knowledge version ${VEO_FAILURE_KNOWLEDGE_VERSION}, ${directives.length} active rules. ` +
    'These rules describe phrasings Vertex AI Veo has refused on prior beats — avoiding them ' +
    'at screenplay authorship time prevents the V4 pipeline from burning sanitization-tier retries ' +
    'or falling back to Kling on content-filter rejections.)';

  const body = directives.map((d, i) => `${i + 1}) ${d}`).join('\n\n');

  return `\n${header}\n\n${body}\n`;
}

/**
 * Apply deterministic regex rewrites to a Veo prompt BEFORE its first
 * submission. Each signature with a non-null preflight_rule is checked in
 * order; matches are replaced with the rule's rewrite string. Returns the
 * (possibly rewritten) prompt and a list of which rules fired — VeoService
 * logs the rewrites at info level for observability.
 *
 * @param {string} prompt
 * @param {Object} [context]
 * @param {string} [context.modelId='veo-3.1-vertex']
 * @param {string[]} [context.personaNames]
 * @returns {{prompt: string, rewrites: Array<{key: string, count: number}>}}
 */
export function applyPreflightRules(prompt, context = {}) {
  const { modelId = 'veo-3.1-vertex' } = context;
  if (!prompt || typeof prompt !== 'string') return { prompt, rewrites: [] };

  let out = prompt;
  const rewrites = [];

  for (const sig of VEO_FAILURE_SIGNATURES) {
    if (sig.status !== 'active') continue;
    if (!sig.preflight_rule) continue;
    if (modelId && !(sig.model_scope || []).includes(modelId)) continue;

    const { regex, flags = 'g', rewrite = '' } = sig.preflight_rule;
    if (!regex) continue;

    let re;
    try {
      re = new RegExp(regex, flags);
    } catch (err) {
      // A malformed regex from a future agent run must not break production.
      // Skip the rule, leave the prompt untouched.
      continue;
    }

    const matches = out.match(re);
    if (matches && matches.length > 0) {
      out = out.replace(re, rewrite);
      rewrites.push({ key: sig.key, count: matches.length });
    }
  }

  // Tidy whitespace + grammatical artefacts left by substitutions
  // (mirrors VeoPromptSanitizer.tidyPrompt to avoid double-rewriting later).
  out = out
    .replace(/\bon\s+in frame\b/gi, 'in frame')
    .replace(/\bat\s+in frame\b/gi, 'in frame')
    .replace(/\bof\s+in frame\b/gi, 'in frame')
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+([.,;:!?])/g, '$1')
    .trim();

  return { prompt: out, rewrites };
}

/**
 * Heuristic — should the caller (a beat generator) opt to regenerate a safer
 * first frame proactively, before Veo submission? Useful when the beat type
 * + persona count + recent image_safety failure rate suggests a high IMAGE-
 * violation probability. Conservative default: false (only regen on detected
 * IMAGE rejection, which is the existing tier2.5 behaviour).
 *
 * @param {Object} beatContext
 * @param {string} [beatContext.beatType]
 * @param {string[]} [beatContext.personaNames]
 * @returns {{shouldRegen: boolean, reason: string}}
 */
export function shouldUseSafeFrameRegen(beatContext = {}) {
  // Initial seed is conservative — return false. The agent populates richer
  // heuristics on subsequent regenerations as the failure dataset grows.
  return { shouldRegen: false, reason: 'no-history-yet' };
}

/**
 * Diagnostic helper — returns a one-shot summary of the current knowledge
 * state. Useful for an admin endpoint or status-line item ("VeoFailure v2026.05.06,
 * 12 active signatures, 4 critical").
 *
 * @returns {{version: string, lastUpdated: string, source: string, activeCount: number, byMode: Object<string, number>, bySeverity: Object<string, number>}}
 */
export function getKnowledgeSummary() {
  const active = VEO_FAILURE_SIGNATURES.filter(s => s.status === 'active');
  const byMode = {};
  const bySeverity = {};
  for (const s of active) {
    byMode[s.failure_mode] = (byMode[s.failure_mode] || 0) + 1;
    bySeverity[s.severity] = (bySeverity[s.severity] || 0) + 1;
  }
  return {
    version: VEO_FAILURE_KNOWLEDGE_VERSION,
    lastUpdated: VEO_FAILURE_LAST_UPDATED,
    source: VEO_FAILURE_SOURCE,
    activeCount: active.length,
    byMode,
    bySeverity
  };
}

export default {
  VEO_FAILURE_KNOWLEDGE_VERSION,
  VEO_FAILURE_LAST_UPDATED,
  VEO_FAILURE_SOURCE,
  VEO_FAILURE_SIGNATURES,
  getGeminiSystemPromptBlock,
  applyPreflightRules,
  shouldUseSafeFrameRegen,
  getKnowledgeSummary
};
