/**
 * TemplateRenderer — Compiles template game code + shared modules + config into final JS.
 *
 * Concatenation order:
 *   1. Shared modules (effects, ui-components, scene-transitions, ambient, audio)
 *   2. Template game.js (reads from window.GAME_TEMPLATE_CONFIG and window.SHARED_FX)
 *   3. Config injection (window.GAME_TEMPLATE_CONFIG = { ... })
 *
 * The result is a single self-contained JavaScript string that can be
 * embedded in the HTML wrapper alongside inlined Phaser.js and asset data URIs.
 */

import { readFileSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SHARED_DIR = join(__dirname, '..', 'shared');
const TEMPLATES_DIR = join(__dirname, '..', 'templates');

// Shared modules loaded in dependency order
const SHARED_MODULES = [
  'effects.js',
  'ui-components.js',
  'scene-transitions.js',
  'ambient.js',
  'audio.js'
];

// Cache for shared modules (read once)
let _sharedCodeCache = null;

/**
 * Load and concatenate all shared modules.
 * @returns {string} Concatenated shared module code
 */
export function loadSharedModules() {
  if (_sharedCodeCache) return _sharedCodeCache;

  const parts = [];
  for (const moduleName of SHARED_MODULES) {
    const filePath = join(SHARED_DIR, moduleName);
    try {
      const code = readFileSync(filePath, 'utf8');
      parts.push(`// === SHARED: ${moduleName} ===`);
      parts.push(code);
    } catch (err) {
      throw new Error(`Failed to load shared module '${moduleName}': ${err.message}`);
    }
  }

  _sharedCodeCache = parts.join('\n\n');
  return _sharedCodeCache;
}

/**
 * Load a template's game.js file.
 * @param {string} templateId  Template directory name (e.g. 'catch-falling')
 * @returns {string}           Template game code
 */
export function loadTemplateCode(templateId) {
  const filePath = join(TEMPLATES_DIR, templateId, 'game.js');
  try {
    return readFileSync(filePath, 'utf8');
  } catch (err) {
    throw new Error(`Failed to load template '${templateId}/game.js': ${err.message}`);
  }
}

/**
 * Load a template's schema.json.
 * @param {string} templateId
 * @returns {object}
 */
export function loadTemplateSchema(templateId) {
  const filePath = join(TEMPLATES_DIR, templateId, 'schema.json');
  try {
    const raw = readFileSync(filePath, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    throw new Error(`Failed to load template '${templateId}/schema.json': ${err.message}`);
  }
}

/**
 * Load a template's defaults.json.
 * @param {string} templateId
 * @returns {object}
 */
export function loadTemplateDefaults(templateId) {
  const filePath = join(TEMPLATES_DIR, templateId, 'defaults.json');
  try {
    const raw = readFileSync(filePath, 'utf8');
    return JSON.parse(raw);
  } catch (err) {
    throw new Error(`Failed to load template '${templateId}/defaults.json': ${err.message}`);
  }
}

/**
 * Compile a complete game JS string from shared modules + template + config.
 *
 * @param {string} templateId  Template directory name
 * @param {object} config      Validated configuration object
 * @returns {string}           Complete game JavaScript
 */
export function compile(templateId, config) {
  const sharedCode = loadSharedModules();
  const templateCode = loadTemplateCode(templateId);

  // Serialize config as JSON and inject it as a window global
  const configJson = JSON.stringify(config, null, 0);

  const parts = [
    '// ═══════════════════════════════════════════════════════════',
    '// PREMIUM HYBRID PLAYABLE AD — Generated by HybridTemplateEngine',
    '// ═══════════════════════════════════════════════════════════',
    '',
    '// --- Configuration ---',
    `window.GAME_TEMPLATE_CONFIG = ${configJson};`,
    '',
    '// --- Shared FX Modules ---',
    sharedCode,
    '',
    '// --- Template: ' + templateId + ' ---',
    templateCode
  ];

  return parts.join('\n');
}

/**
 * List available template IDs by scanning the templates directory.
 * @returns {string[]}
 */
export function listTemplateIds() {
  const entries = readdirSync(TEMPLATES_DIR);
  return entries.filter(entry => {
    const fullPath = join(TEMPLATES_DIR, entry);
    return statSync(fullPath).isDirectory();
  });
}

/**
 * Invalidate the shared modules cache (for dev/hot-reload).
 */
export function clearCache() {
  _sharedCodeCache = null;
}
