-- add_v4_sonic_series_bible.sql
--
-- V4 Audio Coherence Overhaul — Sonic Series Bible at story creation.
--
-- WHY:
--   Episodes currently fragment audio because each scene's `ambient_bed_prompt`
--   is rolled fresh by Gemini in isolation. The Director Agent's verdict
--   (consulted 2026-04-26): the fix is a story-creation-time `sonic_series_bible`
--   that every per-episode `sonic_world` inherits from and varies only what an
--   explicit `inheritance_policy` permits. Hollywood discipline: spine + stems.
--   One world, many angles. The viewer never hears the cut, they hear the world.
--
-- SHAPE (authored once by Gemini at first episode generation, like brand_kit_lut_id):
--
-- {
--   "signature_drone": {
--     "description": "low industrial drone, sub-40Hz HVAC rumble",
--     "frequency_band_hz": [30, 120],
--     "presence_dB": -22
--   },
--   "base_palette": {
--     "ambient_keywords": ["concrete reverb tail", "distant traffic", "HVAC"],
--     "bpm_range": [55, 75],
--     "key_or_modal_center": "F minor / drone-on-F"
--   },
--   "spectral_anchor": {
--     "description": "sustained 60-120Hz hum + faint 2-4kHz air movement",
--     "always_present": true,
--     "level_dB": -18
--   },
--   "foley_density": "naturalistic",
--   "score_under_dialogue": "ducked_-18dB",
--   "silence_as_punctuation": "load_bearing",
--   "diegetic_ratio": 0.7,
--   "transition_grammar": ["j_cut_dominant", "hard_cut_with_room_tone_carry"],
--   "prohibited_instruments": ["orchestral_strings", "synth_pads"],
--   "prohibited_tropes": ["sting_on_reveal", "needle_drop_on_montage"],
--   "prohibited_frequencies_hz": [],
--   "inheritance_policy": {
--     "grammar": "immutable",
--     "no_fly_list": "immutable",
--     "base_palette": "overridable_with_justification",
--     "signature_drone": "must_appear_at_least_once_per_episode"
--   },
--   "reference_shows": ["severance_s1", "andor_s1"],
--   "reference_rationale": "restraint, sub-bass dread, foley-forward"
-- }
--
-- LIFECYCLE:
--   - NULL by default (legacy stories, freshly-created stories before first episode)
--   - Populated lazily on first episode generation via
--     BrandStoryService._generateSonicSeriesBible() — same idempotent pattern
--     as brand_kit_lut_id
--   - Mutable via PATCH /api/brand-stories/:id/sonic-series-bible (Director Panel)
--   - Read by every per-episode screenplay generation as immutable system context
--
-- Purely additive. No existing columns touched. Safe to apply to a live DB.

ALTER TABLE brand_stories
  ADD COLUMN IF NOT EXISTS sonic_series_bible JSONB;

COMMENT ON COLUMN brand_stories.sonic_series_bible IS
  'V4 Sonic Series Bible — locked at story creation (lazy on first episode gen, like brand_kit_lut_id). '
  'Drives every per-episode sonic_world via inheritance_policy. Three pillars: '
  'PALETTE (signature_drone, base_palette, spectral_anchor) + GRAMMAR (foley_density, '
  'score_under_dialogue, silence_as_punctuation, diegetic_ratio, transition_grammar) + '
  'NO-FLY LIST (prohibited_instruments, prohibited_tropes, prohibited_frequencies_hz). '
  'Generated by BrandStoryService._generateSonicSeriesBible() and overridable via the API.';
