-- ============================================
-- BRAND VOICE: GENERATED POSTS HISTORY TABLE
-- Run this in Supabase SQL Editor
-- ============================================
-- Stores all posts generated via Brand Voice so users can review, copy, and reuse them.

CREATE TABLE IF NOT EXISTS brand_voice_generated_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES brand_voice_profiles(id) ON DELETE CASCADE,
  platform TEXT,
  topic TEXT,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bv_generated_user_profile
  ON brand_voice_generated_posts(user_id, profile_id);

CREATE INDEX IF NOT EXISTS idx_bv_generated_created
  ON brand_voice_generated_posts(created_at DESC);

COMMENT ON TABLE brand_voice_generated_posts IS
  'History of posts generated by Brand Voice for review and reuse.';
