-- Brand Story tables for automated short-form video series
-- Supports continuing Reel/Story/TikTok series with consistent personas,
-- AI-generated storylines, storyboard frames, and composite video output.

-- ============================================================
-- brand_stories: Top-level story configuration
-- ============================================================
CREATE TABLE IF NOT EXISTS brand_stories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'active', 'paused', 'completed')),

  -- Persona Configuration
  persona_type TEXT NOT NULL
    CHECK (persona_type IN ('described', 'selected', 'uploaded')),
  persona_config JSONB NOT NULL DEFAULT '{}',
  -- 'described': { description, appearance, voice_style, personality }
  -- 'selected': { heygen_avatar_id, avatar_name, avatar_preview_url }
  -- 'uploaded': { reference_image_urls[], heygen_avatar_group_id, training_status }

  -- Subject / Product
  subject JSONB NOT NULL DEFAULT '{}',
  -- { name, category, description, key_features[], visual_description }

  -- Story Configuration (generated by Gemini)
  storyline JSONB,
  -- { title, theme, genre, tone, target_audience,
  --   arc: { premise, rising_action, climax_hints, resolution_hints },
  --   characters: [{ name, role, personality, visual_description }],
  --   season_bible: "full narrative context for continuity" }

  -- Brand Kit Reference
  brand_kit_job_id UUID REFERENCES media_training_jobs(id) ON DELETE SET NULL,

  -- Leonardo.ai References (for cross-frame character/style consistency)
  leonardo_character_ref_id TEXT,
  leonardo_style_ref_id TEXT,

  -- HeyGen References
  heygen_avatar_group_id TEXT,
  heygen_avatar_id TEXT,

  -- Publishing Config
  target_platforms TEXT[] NOT NULL DEFAULT '{}',
  publish_frequency TEXT NOT NULL DEFAULT 'daily'
    CHECK (publish_frequency IN ('daily', 'every_2_days', 'every_3_days', 'weekly')),

  -- Automation (reuses agent system)
  agent_id UUID REFERENCES agents(id) ON DELETE SET NULL,

  -- Metadata
  total_episodes INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_brand_stories_user_id
  ON brand_stories (user_id);
CREATE INDEX IF NOT EXISTS idx_brand_stories_status
  ON brand_stories (status);
CREATE INDEX IF NOT EXISTS idx_brand_stories_agent_id
  ON brand_stories (agent_id)
  WHERE agent_id IS NOT NULL;

-- RLS
ALTER TABLE brand_stories ENABLE ROW LEVEL SECURITY;

CREATE POLICY brand_stories_user_select ON brand_stories
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY brand_stories_user_insert ON brand_stories
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY brand_stories_user_update ON brand_stories
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY brand_stories_user_delete ON brand_stories
  FOR DELETE USING (auth.uid() = user_id);
-- Service-role bypass (for AutomationManager)
CREATE POLICY brand_stories_service_all ON brand_stories
  FOR ALL USING (auth.role() = 'service_role');

-- ============================================================
-- brand_story_episodes: Individual episodes in a story series
-- ============================================================
CREATE TABLE IF NOT EXISTS brand_story_episodes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id UUID NOT NULL REFERENCES brand_stories(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  episode_number INTEGER NOT NULL,

  -- Scene / Episode Content (generated by Gemini)
  scene_description JSONB NOT NULL DEFAULT '{}',
  -- { title, hook, narrative_beat, dialogue_script, visual_direction,
  --   camera_notes, mood, duration_target_seconds,
  --   continuity_from_previous: "summary of what happened before" }

  -- Storyboard (Leonardo.ai)
  storyboard_frame_url TEXT,
  storyboard_generation_id TEXT,

  -- Avatar Narration (HeyGen)
  avatar_video_url TEXT,
  heygen_video_id TEXT,

  -- Scene Video (Veo / Runway)
  scene_video_url TEXT,
  video_generation_id TEXT,

  -- Final Composite (ffmpeg)
  final_video_url TEXT,
  final_video_storage_path TEXT,

  -- Publishing
  published_at TIMESTAMPTZ,
  publish_results JSONB,
  -- { platform: { success, post_id, url } }

  -- Status Tracking
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN (
      'pending',
      'generating_scene',
      'generating_storyboard',
      'generating_avatar',
      'generating_video',
      'compositing',
      'ready',
      'publishing',
      'published',
      'failed'
    )),
  error_message TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Enforce unique episode numbering per story
  UNIQUE (story_id, episode_number)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_brand_story_episodes_story_id
  ON brand_story_episodes (story_id);
CREATE INDEX IF NOT EXISTS idx_brand_story_episodes_user_id
  ON brand_story_episodes (user_id);
CREATE INDEX IF NOT EXISTS idx_brand_story_episodes_status
  ON brand_story_episodes (status);

-- RLS
ALTER TABLE brand_story_episodes ENABLE ROW LEVEL SECURITY;

CREATE POLICY brand_story_episodes_user_select ON brand_story_episodes
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY brand_story_episodes_user_insert ON brand_story_episodes
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY brand_story_episodes_user_update ON brand_story_episodes
  FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY brand_story_episodes_user_delete ON brand_story_episodes
  FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY brand_story_episodes_service_all ON brand_story_episodes
  FOR ALL USING (auth.role() = 'service_role');
