-- Migration: Add hybrid template engine fields to playable_content
--
-- The Hybrid Template Engine generates premium playable ads using hand-crafted
-- Phaser game templates with AI-generated JSON configuration (vs the legacy
-- AI-generates-everything approach).
--
-- Fields added:
--   * generation_mode   — 'ai_classic' (legacy AI code-gen) | 'hybrid' (premium templates)
--   * template_version  — Semver version of the template engine used (for reproducibility)
--   * template_config   — AI-generated JSON config that was applied to the template

-- 1. Add new columns (nullable — existing rows are treated as ai_classic)
ALTER TABLE public.playable_content
    ADD COLUMN IF NOT EXISTS generation_mode TEXT DEFAULT 'ai_classic'
        CHECK (generation_mode IN ('ai_classic', 'hybrid'));

ALTER TABLE public.playable_content
    ADD COLUMN IF NOT EXISTS template_version TEXT;

ALTER TABLE public.playable_content
    ADD COLUMN IF NOT EXISTS template_config JSONB;

-- 2. Backfill existing rows to 'ai_classic' (they were all generated by the legacy pipeline)
UPDATE public.playable_content
SET generation_mode = 'ai_classic'
WHERE generation_mode IS NULL;

-- 3. Index for querying by generation mode (useful for analytics / filtering)
CREATE INDEX IF NOT EXISTS idx_playable_content_generation_mode
    ON playable_content(generation_mode, created_at DESC);

-- 4. Expand status CHECK to include 'uploading' if not already present
ALTER TABLE public.playable_content DROP CONSTRAINT IF EXISTS playable_content_status_check;
ALTER TABLE public.playable_content
    ADD CONSTRAINT playable_content_status_check
    CHECK (status IN ('pending', 'generating', 'validating', 'packaging', 'uploading', 'completed', 'failed'));
